### ISSUE TITLE
Send only Typing-Guru as response for default courses in dev api

### ISSUE THREAD

**Issue by pysaquib** [navgurukul/sansaar#219]
Also delete demo typing guru from dev server

**Comment by anandpatel504** [comment]
Have removed demo Typing course from dev server.

**Comment by pysaquib** [comment]
`/courses/getCoursesRecommended` This endpoint returns 3 random courses. Make sure one of them is always `typing-guru` ( { course_id: 132 } ) for the time being.
Also put #REVIEW there so we can remove it later after typing app testing and development is done.

**Comment by anandpatel504** [comment]
did set typing guru course as default with two random courses.
