### ISSUE TITLE
Date format for volunteer on boarding Api

### ISSUE THREAD

**Issue by kartiks26** [navgurukul/sansaar#695]
API Reference
The date format is having issue. Please Update.
@kirithiv2000 @mahendra-shah 
![image](https://user-images.githubusercontent.com/84696578/196895864-2c9a3b01-1e67-4cbe-9f6f-17b2e65064b7.png)
![image](https://user-images.githubusercontent.com/84696578/196895913-0a103624-9099-46a9-9155-30bfe30cec46.png)
`POST --> /volunteers/Automation`

**Comment by kirithiv2000** [comment]
fixed
